//**********************************************************************`
//* This is an include file generated by Message Compiler.             *`
//*                                                                    *`
//* Copyright (c) Microsoft Corporation. All Rights Reserved.          *`
//**********************************************************************`
#pragma once

//*****************************************************************************
//
// Notes on the ETW event code generated by MC:
//
// - Structures and arrays of structures are treated as an opaque binary blob.
//   The caller is responsible for packing the data for the structure into a
//   single region of memory, with no padding between values. The macro will
//   have an extra parameter for the length of the blob.
// - Arrays of nul-terminated strings must be packed by the caller into a
//   single binary blob containing the correct number of strings, with a nul
//   after each string. The size of the blob is specified in characters, and
//   includes the final nul.
// - Arrays of SID are treated as a single binary blob. The caller is
//   responsible for packing the SID values into a single region of memory with
//   no padding.
// - The length attribute on the data element in the manifest is significant
//   for values with intype win:UnicodeString, win:AnsiString, or win:Binary.
//   The length attribute must be specified for win:Binary, and is optional for
//   win:UnicodeString and win:AnsiString (if no length is given, the strings
//   are assumed to be nul-terminated). For win:UnicodeString, the length is
//   measured in characters, not bytes.
// - For an array of win:UnicodeString, win:AnsiString, or win:Binary, the
//   length attribute applies to every value in the array, so every value in
//   the array must have the same length. The values in the array are provided
//   to the macro via a single pointer -- the caller is responsible for packing
//   all of the values into a single region of memory with no padding between
//   values.
// - Values of type win:CountedUnicodeString, win:CountedAnsiString, and
//   win:CountedBinary can be generated and collected on Vista or later.
//   However, they may not decode properly without the Windows 10 2018 Fall
//   Update.
// - Arrays of type win:CountedUnicodeString, win:CountedAnsiString, and
//   win:CountedBinary must be packed by the caller into a single region of
//   memory. The format for each item is a UINT16 byte-count followed by that
//   many bytes of data. When providing the array to the generated macro, you
//   must provide the total size of the packed array data, including the UINT16
//   sizes for each item. In the case of win:CountedUnicodeString, the data
//   size is specified in WCHAR (16-bit) units. In the case of
//   win:CountedAnsiString and win:CountedBinary, the data size is specified in
//   bytes.
//
//*****************************************************************************

#include <wmistr.h>
#include <evntrace.h>
#include <evntprov.h>

#ifndef ETW_INLINE
  #ifdef _ETW_KM_
    // In kernel mode, save stack space by never inlining templates.
    #define ETW_INLINE DECLSPEC_NOINLINE __inline
  #else
    // In user mode, save code size by inlining templates as appropriate.
    #define ETW_INLINE __inline
  #endif
#endif // ETW_INLINE

#if defined(__cplusplus)
extern "C" {
#endif

//
// MCGEN_DISABLE_PROVIDER_CODE_GENERATION macro:
// Define this macro to have the compiler skip the generated functions in this
// header.
//
#ifndef MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//
// MCGEN_USE_KERNEL_MODE_APIS macro:
// Controls whether the generated code uses kernel-mode or user-mode APIs.
// - Set to 0 to use Windows user-mode APIs such as EventRegister.
// - Set to 1 to use Windows kernel-mode APIs such as EtwRegister.
// Default is based on whether the _ETW_KM_ macro is defined (i.e. by wdm.h).
// Note that the APIs can also be overridden directly, e.g. by setting the
// MCGEN_EVENTWRITETRANSFER or MCGEN_EVENTREGISTER macros.
//
#ifndef MCGEN_USE_KERNEL_MODE_APIS
  #ifdef _ETW_KM_
    #define MCGEN_USE_KERNEL_MODE_APIS 1
  #else
    #define MCGEN_USE_KERNEL_MODE_APIS 0
  #endif
#endif // MCGEN_USE_KERNEL_MODE_APIS

//
// MCGEN_HAVE_EVENTSETINFORMATION macro:
// Controls how McGenEventSetInformation uses the EventSetInformation API.
// - Set to 0 to disable the use of EventSetInformation
//   (McGenEventSetInformation will always return an error).
// - Set to 1 to directly invoke MCGEN_EVENTSETINFORMATION.
// - Set to 2 to to locate EventSetInformation at runtime via GetProcAddress
//   (user-mode) or MmGetSystemRoutineAddress (kernel-mode).
// Default is determined as follows:
// - If MCGEN_EVENTSETINFORMATION has been customized, set to 1
//   (i.e. use MCGEN_EVENTSETINFORMATION).
// - Else if the target OS version has EventSetInformation, set to 1
//   (i.e. use MCGEN_EVENTSETINFORMATION).
// - Else set to 2 (i.e. try to dynamically locate EventSetInformation).
// Note that an McGenEventSetInformation function will only be generated if one
// or more provider in a manifest has provider traits.
//
#ifndef MCGEN_HAVE_EVENTSETINFORMATION
  #ifdef MCGEN_EVENTSETINFORMATION             // if MCGEN_EVENTSETINFORMATION has been customized,
    #define MCGEN_HAVE_EVENTSETINFORMATION   1 //   directly invoke MCGEN_EVENTSETINFORMATION(...).
  #elif MCGEN_USE_KERNEL_MODE_APIS             // else if using kernel-mode APIs,
    #if NTDDI_VERSION >= 0x06040000            //   if target OS is Windows 10 or later,
      #define MCGEN_HAVE_EVENTSETINFORMATION 1 //     directly invoke MCGEN_EVENTSETINFORMATION(...).
    #else                                      //   else
      #define MCGEN_HAVE_EVENTSETINFORMATION 2 //     find "EtwSetInformation" via MmGetSystemRoutineAddress.
    #endif                                     // else (using user-mode APIs)
  #else                                        //   if target OS and SDK is Windows 8 or later,
    #if WINVER >= 0x0602 && defined(EVENT_FILTER_TYPE_SCHEMATIZED)
      #define MCGEN_HAVE_EVENTSETINFORMATION 1 //     directly invoke MCGEN_EVENTSETINFORMATION(...).
    #else                                      //   else
      #define MCGEN_HAVE_EVENTSETINFORMATION 2 //     find "EventSetInformation" via GetModuleHandleExW/GetProcAddress.
    #endif
  #endif
#endif // MCGEN_HAVE_EVENTSETINFORMATION

//
// MCGEN Override Macros
//
// The following override macros may be defined before including this header
// to control the APIs used by this header:
//
// - MCGEN_EVENTREGISTER
// - MCGEN_EVENTUNREGISTER
// - MCGEN_EVENTSETINFORMATION
// - MCGEN_EVENTWRITETRANSFER
//
// If the the macro is undefined, the MC implementation will default to the
// corresponding ETW APIs. For example, if the MCGEN_EVENTREGISTER macro is
// undefined, the EventRegister[MyProviderName] macro will use EventRegister
// in user mode and will use EtwRegister in kernel mode.
//
// To prevent issues from conflicting definitions of these macros, the value
// of the override macro will be used as a suffix in certain internal function
// names. Because of this, the override macros must follow certain rules:
//
// - The macro must be defined before any MC-generated header is included and
//   must not be undefined or redefined after any MC-generated header is
//   included. Different translation units (i.e. different .c or .cpp files)
//   may set the macros to different values, but within a translation unit
//   (within a single .c or .cpp file), the macro must be set once and not
//   changed.
// - The override must be an object-like macro, not a function-like macro
//   (i.e. the override macro must not have a parameter list).
// - The override macro's value must be a simple identifier, i.e. must be
//   something that starts with a letter or '_' and contains only letters,
//   numbers, and '_' characters.
// - If the override macro's value is the name of a second object-like macro,
//   the second object-like macro must follow the same rules. (The override
//   macro's value can also be the name of a function-like macro, in which
//   case the function-like macro does not need to follow the same rules.)
//
// For example, the following will cause compile errors:
//
//   #define MCGEN_EVENTWRITETRANSFER MyNamespace::MyClass::MyFunction // Value has non-identifier characters (colon).
//   #define MCGEN_EVENTWRITETRANSFER GetEventWriteFunctionPointer(7)  // Value has non-identifier characters (parentheses).
//   #define MCGEN_EVENTWRITETRANSFER(h,e,a,r,c,d) EventWrite(h,e,c,d) // Override is defined as a function-like macro.
//   #define MY_OBJECT_LIKE_MACRO     MyNamespace::MyClass::MyEventWriteFunction
//   #define MCGEN_EVENTWRITETRANSFER MY_OBJECT_LIKE_MACRO // Evaluates to something with non-identifier characters (colon).
//
// The following would be ok:
//
//   #define MCGEN_EVENTWRITETRANSFER  MyEventWriteFunction1  // OK, suffix will be "MyEventWriteFunction1".
//   #define MY_OBJECT_LIKE_MACRO      MyEventWriteFunction2
//   #define MCGEN_EVENTWRITETRANSFER  MY_OBJECT_LIKE_MACRO   // OK, suffix will be "MyEventWriteFunction2".
//   #define MY_FUNCTION_LIKE_MACRO(h,e,a,r,c,d) MyNamespace::MyClass::MyEventWriteFunction3(h,e,c,d)
//   #define MCGEN_EVENTWRITETRANSFER  MY_FUNCTION_LIKE_MACRO // OK, suffix will be "MY_FUNCTION_LIKE_MACRO".
//
#ifndef MCGEN_EVENTREGISTER
  #if MCGEN_USE_KERNEL_MODE_APIS
    #define MCGEN_EVENTREGISTER        EtwRegister
  #else
    #define MCGEN_EVENTREGISTER        EventRegister
  #endif
#endif // MCGEN_EVENTREGISTER
#ifndef MCGEN_EVENTUNREGISTER
  #if MCGEN_USE_KERNEL_MODE_APIS
    #define MCGEN_EVENTUNREGISTER      EtwUnregister
  #else
    #define MCGEN_EVENTUNREGISTER      EventUnregister
  #endif
#endif // MCGEN_EVENTUNREGISTER
#ifndef MCGEN_EVENTSETINFORMATION
  #if MCGEN_USE_KERNEL_MODE_APIS
    #define MCGEN_EVENTSETINFORMATION  EtwSetInformation
  #else
    #define MCGEN_EVENTSETINFORMATION  EventSetInformation
  #endif
#endif // MCGEN_EVENTSETINFORMATION
#ifndef MCGEN_EVENTWRITETRANSFER
  #if MCGEN_USE_KERNEL_MODE_APIS
    #define MCGEN_EVENTWRITETRANSFER   EtwWriteTransfer
  #else
    #define MCGEN_EVENTWRITETRANSFER   EventWriteTransfer
  #endif
#endif // MCGEN_EVENTWRITETRANSFER

//
// MCGEN_EVENT_ENABLED macro:
// Override to control how the EventWrite[EventName] macros determine whether
// an event is enabled. The default behavior is for EventWrite[EventName] to
// use the EventEnabled[EventName] macros.
//
#ifndef MCGEN_EVENT_ENABLED
#define MCGEN_EVENT_ENABLED(EventName) EventEnabled##EventName()
#endif

//
// MCGEN_EVENT_ENABLED_FORCONTEXT macro:
// Override to control how the EventWrite[EventName]_ForContext macros
// determine whether an event is enabled. The default behavior is for
// EventWrite[EventName]_ForContext to use the
// EventEnabled[EventName]_ForContext macros.
//
#ifndef MCGEN_EVENT_ENABLED_FORCONTEXT
#define MCGEN_EVENT_ENABLED_FORCONTEXT(pContext, EventName) EventEnabled##EventName##_ForContext(pContext)
#endif

//
// MCGEN_ENABLE_CHECK macro:
// Determines whether the specified event would be considered as enabled
// based on the state of the specified context. Slightly faster than calling
// McGenEventEnabled directly.
//
#ifndef MCGEN_ENABLE_CHECK
#define MCGEN_ENABLE_CHECK(Context, Descriptor) (Context.IsEnabled && McGenEventEnabled(&Context, &Descriptor))
#endif

#if !defined(MCGEN_TRACE_CONTEXT_DEF)
#define MCGEN_TRACE_CONTEXT_DEF
// This structure is for use by MC-generated code and should not be used directly.
typedef struct _MCGEN_TRACE_CONTEXT
{
    TRACEHANDLE            RegistrationHandle;
    TRACEHANDLE            Logger;      // Used as pointer to provider traits.
    ULONGLONG              MatchAnyKeyword;
    ULONGLONG              MatchAllKeyword;
    ULONG                  Flags;
    ULONG                  IsEnabled;
    UCHAR                  Level;
    UCHAR                  Reserve;
    USHORT                 EnableBitsCount;
    PULONG                 EnableBitMask;
    const ULONGLONG*       EnableKeyWords;
    const UCHAR*           EnableLevel;
} MCGEN_TRACE_CONTEXT, *PMCGEN_TRACE_CONTEXT;
#endif // MCGEN_TRACE_CONTEXT_DEF

#if !defined(MCGEN_LEVEL_KEYWORD_ENABLED_DEF)
#define MCGEN_LEVEL_KEYWORD_ENABLED_DEF
//
// Determines whether an event with a given Level and Keyword would be
// considered as enabled based on the state of the specified context.
// Note that you may want to use MCGEN_ENABLE_CHECK instead of calling this
// function directly.
//
FORCEINLINE
BOOLEAN
McGenLevelKeywordEnabled(
    _In_ PMCGEN_TRACE_CONTEXT EnableInfo,
    _In_ UCHAR Level,
    _In_ ULONGLONG Keyword
    )
{
    //
    // Check if the event Level is lower than the level at which
    // the channel is enabled.
    // If the event Level is 0 or the channel is enabled at level 0,
    // all levels are enabled.
    //

    if ((Level <= EnableInfo->Level) || // This also covers the case of Level == 0.
        (EnableInfo->Level == 0)) {

        //
        // Check if Keyword is enabled
        //

        if ((Keyword == (ULONGLONG)0) ||
            ((Keyword & EnableInfo->MatchAnyKeyword) &&
             ((Keyword & EnableInfo->MatchAllKeyword) == EnableInfo->MatchAllKeyword))) {
            return TRUE;
        }
    }

    return FALSE;
}
#endif // MCGEN_LEVEL_KEYWORD_ENABLED_DEF

#if !defined(MCGEN_EVENT_ENABLED_DEF)
#define MCGEN_EVENT_ENABLED_DEF
//
// Determines whether the specified event would be considered as enabled based
// on the state of the specified context. Note that you may want to use
// MCGEN_ENABLE_CHECK instead of calling this function directly.
//
FORCEINLINE
BOOLEAN
McGenEventEnabled(
    _In_ PMCGEN_TRACE_CONTEXT EnableInfo,
    _In_ PCEVENT_DESCRIPTOR EventDescriptor
    )
{
    return McGenLevelKeywordEnabled(EnableInfo, EventDescriptor->Level, EventDescriptor->Keyword);
}
#endif // MCGEN_EVENT_ENABLED_DEF

#if !defined(MCGEN_CONTROL_CALLBACK)
#define MCGEN_CONTROL_CALLBACK

// This function is for use by MC-generated code and should not be used directly.
DECLSPEC_NOINLINE __inline
VOID
__stdcall
McGenControlCallbackV2(
    _In_ LPCGUID SourceId,
    _In_ ULONG ControlCode,
    _In_ UCHAR Level,
    _In_ ULONGLONG MatchAnyKeyword,
    _In_ ULONGLONG MatchAllKeyword,
    _In_opt_ PEVENT_FILTER_DESCRIPTOR FilterData,
    _Inout_opt_ PVOID CallbackContext
    )
/*++

Routine Description:

    This is the notification callback for Windows Vista and later.

Arguments:

    SourceId - The GUID that identifies the session that enabled the provider.

    ControlCode - The parameter indicates whether the provider
                  is being enabled or disabled.

    Level - The level at which the event is enabled.

    MatchAnyKeyword - The bitmask of keywords that the provider uses to
                      determine the category of events that it writes.

    MatchAllKeyword - This bitmask additionally restricts the category
                      of events that the provider writes.

    FilterData - The provider-defined data.

    CallbackContext - The context of the callback that is defined when the provider
                      called EtwRegister to register itself.

Remarks:

    ETW calls this function to notify provider of enable/disable

--*/
{
    PMCGEN_TRACE_CONTEXT Ctx = (PMCGEN_TRACE_CONTEXT)CallbackContext;
    ULONG Ix;
#ifndef MCGEN_PRIVATE_ENABLE_CALLBACK_V2
    UNREFERENCED_PARAMETER(SourceId);
    UNREFERENCED_PARAMETER(FilterData);
#endif

    if (Ctx == NULL) {
        return;
    }

    switch (ControlCode) {

        case EVENT_CONTROL_CODE_ENABLE_PROVIDER:
            Ctx->Level = Level;
            Ctx->MatchAnyKeyword = MatchAnyKeyword;
            Ctx->MatchAllKeyword = MatchAllKeyword;
            Ctx->IsEnabled = EVENT_CONTROL_CODE_ENABLE_PROVIDER;

            for (Ix = 0; Ix < Ctx->EnableBitsCount; Ix += 1) {
                if (McGenLevelKeywordEnabled(Ctx, Ctx->EnableLevel[Ix], Ctx->EnableKeyWords[Ix]) != FALSE) {
                    Ctx->EnableBitMask[Ix >> 5] |= (1 << (Ix % 32));
                } else {
                    Ctx->EnableBitMask[Ix >> 5] &= ~(1 << (Ix % 32));
                }
            }
            break;

        case EVENT_CONTROL_CODE_DISABLE_PROVIDER:
            Ctx->IsEnabled = EVENT_CONTROL_CODE_DISABLE_PROVIDER;
            Ctx->Level = 0;
            Ctx->MatchAnyKeyword = 0;
            Ctx->MatchAllKeyword = 0;
            if (Ctx->EnableBitsCount > 0) {
#pragma warning(suppress: 26451) // Arithmetic overflow cannot occur, no matter the value of EnableBitCount
                RtlZeroMemory(Ctx->EnableBitMask, (((Ctx->EnableBitsCount - 1) / 32) + 1) * sizeof(ULONG));
            }
            break;

        default:
            break;
    }

#ifdef MCGEN_PRIVATE_ENABLE_CALLBACK_V2
    //
    // Call user defined callback
    //
    MCGEN_PRIVATE_ENABLE_CALLBACK_V2(
        SourceId,
        ControlCode,
        Level,
        MatchAnyKeyword,
        MatchAllKeyword,
        FilterData,
        CallbackContext
        );
#endif // MCGEN_PRIVATE_ENABLE_CALLBACK_V2

    return;
}

#endif // MCGEN_CONTROL_CALLBACK

#ifndef _mcgen_PENABLECALLBACK
  #if MCGEN_USE_KERNEL_MODE_APIS
    #define _mcgen_PENABLECALLBACK      PETWENABLECALLBACK
  #else
    #define _mcgen_PENABLECALLBACK      PENABLECALLBACK
  #endif
#endif // _mcgen_PENABLECALLBACK

#if !defined(_mcgen_PASTE2)
// This macro is for use by MC-generated code and should not be used directly.
#define _mcgen_PASTE2(a, b) _mcgen_PASTE2_imp(a, b)
#define _mcgen_PASTE2_imp(a, b) a##b
#endif // _mcgen_PASTE2

#if !defined(_mcgen_PASTE3)
// This macro is for use by MC-generated code and should not be used directly.
#define _mcgen_PASTE3(a, b, c) _mcgen_PASTE3_imp(a, b, c)
#define _mcgen_PASTE3_imp(a, b, c) a##b##_##c
#endif // _mcgen_PASTE3

//
// Macro validation
//

// Validate MCGEN_EVENTREGISTER:

// Trigger an error if MCGEN_EVENTREGISTER is not an unqualified (simple) identifier:
struct _mcgen_PASTE2(MCGEN_EVENTREGISTER_definition_must_be_an_unqualified_identifier_, MCGEN_EVENTREGISTER);

// Trigger an error if MCGEN_EVENTREGISTER is redefined:
typedef struct _mcgen_PASTE2(MCGEN_EVENTREGISTER_definition_must_be_an_unqualified_identifier_, MCGEN_EVENTREGISTER)
    MCGEN_EVENTREGISTER_must_not_be_redefined_between_headers;

// Trigger an error if MCGEN_EVENTREGISTER is defined as a function-like macro:
typedef void MCGEN_EVENTREGISTER_must_not_be_a_functionLike_macro_MCGEN_EVENTREGISTER;
typedef int _mcgen_PASTE2(MCGEN_EVENTREGISTER_must_not_be_a_functionLike_macro_, MCGEN_EVENTREGISTER);

// Validate MCGEN_EVENTUNREGISTER:

// Trigger an error if MCGEN_EVENTUNREGISTER is not an unqualified (simple) identifier:
struct _mcgen_PASTE2(MCGEN_EVENTUNREGISTER_definition_must_be_an_unqualified_identifier_, MCGEN_EVENTUNREGISTER);

// Trigger an error if MCGEN_EVENTUNREGISTER is redefined:
typedef struct _mcgen_PASTE2(MCGEN_EVENTUNREGISTER_definition_must_be_an_unqualified_identifier_, MCGEN_EVENTUNREGISTER)
    MCGEN_EVENTUNREGISTER_must_not_be_redefined_between_headers;

// Trigger an error if MCGEN_EVENTUNREGISTER is defined as a function-like macro:
typedef void MCGEN_EVENTUNREGISTER_must_not_be_a_functionLike_macro_MCGEN_EVENTUNREGISTER;
typedef int _mcgen_PASTE2(MCGEN_EVENTUNREGISTER_must_not_be_a_functionLike_macro_, MCGEN_EVENTUNREGISTER);

// Validate MCGEN_EVENTSETINFORMATION:

// Trigger an error if MCGEN_EVENTSETINFORMATION is not an unqualified (simple) identifier:
struct _mcgen_PASTE2(MCGEN_EVENTSETINFORMATION_definition_must_be_an_unqualified_identifier_, MCGEN_EVENTSETINFORMATION);

// Trigger an error if MCGEN_EVENTSETINFORMATION is redefined:
typedef struct _mcgen_PASTE2(MCGEN_EVENTSETINFORMATION_definition_must_be_an_unqualified_identifier_, MCGEN_EVENTSETINFORMATION)
    MCGEN_EVENTSETINFORMATION_must_not_be_redefined_between_headers;

// Trigger an error if MCGEN_EVENTSETINFORMATION is defined as a function-like macro:
typedef void MCGEN_EVENTSETINFORMATION_must_not_be_a_functionLike_macro_MCGEN_EVENTSETINFORMATION;
typedef int _mcgen_PASTE2(MCGEN_EVENTSETINFORMATION_must_not_be_a_functionLike_macro_, MCGEN_EVENTSETINFORMATION);

// Validate MCGEN_EVENTWRITETRANSFER:

// Trigger an error if MCGEN_EVENTWRITETRANSFER is not an unqualified (simple) identifier:
struct _mcgen_PASTE2(MCGEN_EVENTWRITETRANSFER_definition_must_be_an_unqualified_identifier_, MCGEN_EVENTWRITETRANSFER);

// Trigger an error if MCGEN_EVENTWRITETRANSFER is redefined:
typedef struct _mcgen_PASTE2(MCGEN_EVENTWRITETRANSFER_definition_must_be_an_unqualified_identifier_, MCGEN_EVENTWRITETRANSFER)
    MCGEN_EVENTWRITETRANSFER_must_not_be_redefined_between_headers;;

// Trigger an error if MCGEN_EVENTWRITETRANSFER is defined as a function-like macro:
typedef void MCGEN_EVENTWRITETRANSFER_must_not_be_a_functionLike_macro_MCGEN_EVENTWRITETRANSFER;
typedef int _mcgen_PASTE2(MCGEN_EVENTWRITETRANSFER_must_not_be_a_functionLike_macro_, MCGEN_EVENTWRITETRANSFER);

#ifndef McGenEventWrite_def
#define McGenEventWrite_def

// This macro is for use by MC-generated code and should not be used directly.
#define McGenEventWrite _mcgen_PASTE2(McGenEventWrite_, MCGEN_EVENTWRITETRANSFER)

// This function is for use by MC-generated code and should not be used directly.
DECLSPEC_NOINLINE __inline
ULONG __stdcall
McGenEventWrite(
    _In_ PMCGEN_TRACE_CONTEXT Context,
    _In_ PCEVENT_DESCRIPTOR Descriptor,
    _In_opt_ LPCGUID ActivityId,
    _In_range_(1, 128) ULONG EventDataCount,
    _Pre_cap_(EventDataCount) EVENT_DATA_DESCRIPTOR* EventData
    )
{
    const USHORT UNALIGNED* Traits;

    // Some customized MCGEN_EVENTWRITETRANSFER macros might ignore ActivityId.
    UNREFERENCED_PARAMETER(ActivityId);

    Traits = (const USHORT UNALIGNED*)(UINT_PTR)Context->Logger;

    if (Traits == NULL) {
        EventData[0].Ptr = 0;
        EventData[0].Size = 0;
        EventData[0].Reserved = 0;
    } else {
        EventData[0].Ptr = (ULONG_PTR)Traits;
        EventData[0].Size = *Traits;
        EventData[0].Reserved = 2; // EVENT_DATA_DESCRIPTOR_TYPE_PROVIDER_METADATA
    }

    return MCGEN_EVENTWRITETRANSFER(
        Context->RegistrationHandle,
        Descriptor,
        ActivityId,
        NULL,
        EventDataCount,
        EventData);
}
#endif // McGenEventWrite_def

#if !defined(McGenEventRegisterUnregister)
#define McGenEventRegisterUnregister

// This macro is for use by MC-generated code and should not be used directly.
#define McGenEventRegister _mcgen_PASTE2(McGenEventRegister_, MCGEN_EVENTREGISTER)

#pragma warning(push)
#pragma warning(disable:6103)
// This function is for use by MC-generated code and should not be used directly.
DECLSPEC_NOINLINE __inline
ULONG __stdcall
McGenEventRegister(
    _In_ LPCGUID ProviderId,
    _In_opt_ _mcgen_PENABLECALLBACK EnableCallback,
    _In_opt_ PVOID CallbackContext,
    _Inout_ PREGHANDLE RegHandle
    )
/*++

Routine Description:

    This function registers the provider with ETW.

Arguments:

    ProviderId - Provider ID to register with ETW.

    EnableCallback - Callback to be used.

    CallbackContext - Context for the callback.

    RegHandle - Pointer to registration handle.

Remarks:

    Should not be called if the provider is already registered (i.e. should not
    be called if *RegHandle != 0). Repeatedly registering a provider is a bug
    and may indicate a race condition. However, for compatibility with previous
    behavior, this function will return SUCCESS in this case.

--*/
{
    ULONG Error;

    if (*RegHandle != 0)
    {
        Error = 0; // ERROR_SUCCESS
    }
    else
    {
        Error = MCGEN_EVENTREGISTER(ProviderId, EnableCallback, CallbackContext, RegHandle);
    }

    return Error;
}
#pragma warning(pop)

// This macro is for use by MC-generated code and should not be used directly.
#define McGenEventUnregister _mcgen_PASTE2(McGenEventUnregister_, MCGEN_EVENTUNREGISTER)

// This function is for use by MC-generated code and should not be used directly.
DECLSPEC_NOINLINE __inline
ULONG __stdcall
McGenEventUnregister(_Inout_ PREGHANDLE RegHandle)
/*++

Routine Description:

    Unregister from ETW and set *RegHandle = 0.

Arguments:

    RegHandle - the pointer to the provider registration handle

Remarks:

    If provider has not been registered (i.e. if *RegHandle == 0),
    return SUCCESS. It is safe to call McGenEventUnregister even if the
    call to McGenEventRegister returned an error.

--*/
{
    ULONG Error;

    if(*RegHandle == 0)
    {
        Error = 0; // ERROR_SUCCESS
    }
    else
    {
        Error = MCGEN_EVENTUNREGISTER(*RegHandle);
        *RegHandle = (REGHANDLE)0;
    }

    return Error;
}

#endif // McGenEventRegisterUnregister

#ifndef _mcgen_EVENT_BIT_SET
  #if defined(_M_IX86) || defined(_M_X64)
    // This macro is for use by MC-generated code and should not be used directly.
    #define _mcgen_EVENT_BIT_SET(EnableBits, BitPosition) ((((const unsigned char*)EnableBits)[BitPosition >> 3] & (1u << (BitPosition & 7))) != 0)
  #else // CPU type
    // This macro is for use by MC-generated code and should not be used directly.
    #define _mcgen_EVENT_BIT_SET(EnableBits, BitPosition) ((EnableBits[BitPosition >> 5] & (1u << (BitPosition & 31))) != 0)
  #endif // CPU type
#endif // _mcgen_EVENT_BIT_SET

#endif // MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// Provider "Fishbowl" event count 8
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Provider GUID = 0e28e4c0-89f9-4b9d-9f35-bd497b26c397
EXTERN_C __declspec(selectany) const GUID FISHBOWL_PROVIDER = {0x0e28e4c0, 0x89f9, 0x4b9d, {0x9f, 0x35, 0xbd, 0x49, 0x7b, 0x26, 0xc3, 0x97}};

#ifndef FISHBOWL_PROVIDER_Traits
#define FISHBOWL_PROVIDER_Traits NULL
#endif // FISHBOWL_PROVIDER_Traits

//
// Channel
//
#define FISHBOWL_CHANNEL_OPERATIONAL 0x10
#define FISHBOWL_CHANNEL_OPERATIONAL_KEYWORD 0x8000000000000000

//
// Tasks
//
#define TASK_PROCESS_EXEC 0x1
#define TASK_PROCESS_EXIT 0x2
#define TASK_CREDENTIAL_ACCESS 0x3
#define TASK_NETWORK_EGRESS 0x4
#define TASK_FILE_WRITE 0x5
#define TASK_PROMPT 0xa
#define TASK_TOOL_CALL 0xb
#define TASK_TOOL_RESULT 0xc

//
// Event Descriptors
//
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR EVT_PROCESS_EXEC = {0x1, 0x0, 0x10, 0x4, 0x0, 0x1, 0x8000000000000000};
#define EVT_PROCESS_EXEC_value 0x1
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR EVT_PROCESS_EXIT = {0x2, 0x0, 0x10, 0x4, 0x0, 0x2, 0x8000000000000000};
#define EVT_PROCESS_EXIT_value 0x2
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR EVT_CREDENTIAL_ACCESS = {0x3, 0x0, 0x10, 0x3, 0x0, 0x3, 0x8000000000000000};
#define EVT_CREDENTIAL_ACCESS_value 0x3
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR EVT_NETWORK_EGRESS = {0x4, 0x0, 0x10, 0x3, 0x0, 0x4, 0x8000000000000000};
#define EVT_NETWORK_EGRESS_value 0x4
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR EVT_FILE_WRITE = {0x5, 0x0, 0x10, 0x4, 0x0, 0x5, 0x8000000000000000};
#define EVT_FILE_WRITE_value 0x5
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR EVT_PROMPT = {0xa, 0x0, 0x10, 0x4, 0x0, 0xa, 0x8000000000000000};
#define EVT_PROMPT_value 0xa
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR EVT_TOOL_CALL = {0xb, 0x0, 0x10, 0x4, 0x0, 0xb, 0x8000000000000000};
#define EVT_TOOL_CALL_value 0xb
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR EVT_TOOL_RESULT = {0xc, 0x0, 0x10, 0x4, 0x0, 0xc, 0x8000000000000000};
#define EVT_TOOL_RESULT_value 0xc

//
// MCGEN_DISABLE_PROVIDER_CODE_GENERATION macro:
// Define this macro to have the compiler skip the generated functions in this
// header.
//
#ifndef MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//
// Event Enablement Bits
// These variables are for use by MC-generated code and should not be used directly.
//
EXTERN_C __declspec(selectany) DECLSPEC_CACHEALIGN ULONG FishbowlEnableBits[1];
EXTERN_C __declspec(selectany) const ULONGLONG FishbowlKeywords[2] = {0x8000000000000000, 0x8000000000000000};
EXTERN_C __declspec(selectany) const unsigned char FishbowlLevels[2] = {4, 3};

//
// Provider context
//
EXTERN_C __declspec(selectany) MCGEN_TRACE_CONTEXT FISHBOWL_PROVIDER_Context = {0, (ULONG_PTR)FISHBOWL_PROVIDER_Traits, 0, 0, 0, 0, 0, 0, 2, FishbowlEnableBits, FishbowlKeywords, FishbowlLevels};

//
// Provider REGHANDLE
//
#define FishbowlHandle (FISHBOWL_PROVIDER_Context.RegistrationHandle)

//
// This macro is set to 0, indicating that the EventWrite[Name] macros do not
// have an Activity parameter. This is controlled by the -km and -um options.
//
#define FISHBOWL_PROVIDER_EventWriteActivity 0

//
// Register with ETW using the control GUID specified in the manifest.
// Invoke this macro during module initialization (i.e. program startup,
// DLL process attach, or driver load) to initialize the provider.
// Note that if this function returns an error, the error means that
// will not work, but no action needs to be taken -- even if EventRegister
// returns an error, it is generally safe to use EventWrite and
// EventUnregister macros (they will be no-ops if EventRegister failed).
//
#ifndef EventRegisterFishbowl
#define EventRegisterFishbowl() McGenEventRegister(&FISHBOWL_PROVIDER, McGenControlCallbackV2, &FISHBOWL_PROVIDER_Context, &FishbowlHandle)
#endif

//
// Register with ETW using a specific control GUID (i.e. a GUID other than what
// is specified in the manifest). Advanced scenarios only.
//
#ifndef EventRegisterByGuidFishbowl
#define EventRegisterByGuidFishbowl(Guid) McGenEventRegister(&(Guid), McGenControlCallbackV2, &FISHBOWL_PROVIDER_Context, &FishbowlHandle)
#endif

//
// Unregister with ETW and close the provider.
// Invoke this macro during module shutdown (i.e. program exit, DLL process
// detach, or driver unload) to unregister the provider.
// Note that you MUST call EventUnregister before DLL or driver unload
// (not optional): failure to unregister a provider before DLL or driver unload
// will result in crashes.
//
#ifndef EventUnregisterFishbowl
#define EventUnregisterFishbowl() McGenEventUnregister(&FishbowlHandle)
#endif

//
// MCGEN_ENABLE_FORCONTEXT_CODE_GENERATION macro:
// Define this macro to enable support for caller-allocated provider context.
//
#ifdef MCGEN_ENABLE_FORCONTEXT_CODE_GENERATION

//
// Advanced scenarios: Caller-allocated provider context.
// Use when multiple differently-configured provider handles are needed,
// e.g. for container-aware drivers, one context per container.
//
// Usage:
//
// - Caller enables the feature before including this header, e.g.
//   #define MCGEN_ENABLE_FORCONTEXT_CODE_GENERATION 1
// - Caller allocates memory, e.g. pContext = malloc(sizeof(McGenContext_Fishbowl));
// - Caller registers the provider, e.g. EventRegisterFishbowl_ForContext(pContext);
// - Caller writes events, e.g. EventWriteMyEvent_ForContext(pContext, ...);
// - Caller unregisters, e.g. EventUnregisterFishbowl_ForContext(pContext);
// - Caller frees memory, e.g. free(pContext);
//

typedef struct tagMcGenContext_Fishbowl {
    // The fields of this structure are subject to change and should
    // not be accessed directly. To access the provider's REGHANDLE,
    // use FishbowlHandle_ForContext(pContext).
    MCGEN_TRACE_CONTEXT Context;
    ULONG EnableBits[1];
} McGenContext_Fishbowl;

#define EventRegisterFishbowl_ForContext(pContext)             _mcgen_PASTE2(_mcgen_RegisterForContext_Fishbowl_, MCGEN_EVENTREGISTER)(&FISHBOWL_PROVIDER, pContext)
#define EventRegisterByGuidFishbowl_ForContext(Guid, pContext) _mcgen_PASTE2(_mcgen_RegisterForContext_Fishbowl_, MCGEN_EVENTREGISTER)(&(Guid), pContext)
#define EventUnregisterFishbowl_ForContext(pContext)           McGenEventUnregister(&(pContext)->Context.RegistrationHandle)

//
// Provider REGHANDLE for caller-allocated context.
//
#define FishbowlHandle_ForContext(pContext) ((pContext)->Context.RegistrationHandle)

// This function is for use by MC-generated code and should not be used directly.
// Initialize and register the caller-allocated context.
__inline
ULONG __stdcall
_mcgen_PASTE2(_mcgen_RegisterForContext_Fishbowl_, MCGEN_EVENTREGISTER)(
    _In_ LPCGUID pProviderId,
    _Out_ McGenContext_Fishbowl* pContext)
{
    RtlZeroMemory(pContext, sizeof(*pContext));
    pContext->Context.Logger = (ULONG_PTR)FISHBOWL_PROVIDER_Traits;
    pContext->Context.EnableBitsCount = 2;
    pContext->Context.EnableBitMask = pContext->EnableBits;
    pContext->Context.EnableKeyWords = FishbowlKeywords;
    pContext->Context.EnableLevel = FishbowlLevels;
    return McGenEventRegister(
        pProviderId,
        McGenControlCallbackV2,
        &pContext->Context,
        &pContext->Context.RegistrationHandle);
}

// This function is for use by MC-generated code and should not be used directly.
// Trigger a compile error if called with the wrong parameter type.
FORCEINLINE
_Ret_ McGenContext_Fishbowl*
_mcgen_CheckContextType_Fishbowl(_In_ McGenContext_Fishbowl* pContext)
{
    return pContext;
}

#endif // MCGEN_ENABLE_FORCONTEXT_CODE_GENERATION

//
// Enablement check macro for event "EVT_PROCESS_EXEC"
//
#define EventEnabledEVT_PROCESS_EXEC() _mcgen_EVENT_BIT_SET(FishbowlEnableBits, 0)
#define EventEnabledEVT_PROCESS_EXEC_ForContext(pContext) _mcgen_EVENT_BIT_SET(_mcgen_CheckContextType_Fishbowl(pContext)->EnableBits, 0)

//
// Event write macros for event "EVT_PROCESS_EXEC"
//
#define EventWriteEVT_PROCESS_EXEC(Timestamp, HostId, AgentId, UserId, Pid, Ppid, ProcessName, ProcessPath, CommandLine, User, AgentRootPid, AttributedByDescent, RequestedInToolResult, TriggeringCommand, TriggeringPrompt, ParentChain, ExecArgs, RawJson) \
        MCGEN_EVENT_ENABLED(EVT_PROCESS_EXEC) \
        ? _mcgen_TEMPLATE_FOR_EVT_PROCESS_EXEC(&FISHBOWL_PROVIDER_Context, &EVT_PROCESS_EXEC, Timestamp, HostId, AgentId, UserId, Pid, Ppid, ProcessName, ProcessPath, CommandLine, User, AgentRootPid, AttributedByDescent, RequestedInToolResult, TriggeringCommand, TriggeringPrompt, ParentChain, ExecArgs, RawJson) : 0
#define EventWriteEVT_PROCESS_EXEC_AssumeEnabled(Timestamp, HostId, AgentId, UserId, Pid, Ppid, ProcessName, ProcessPath, CommandLine, User, AgentRootPid, AttributedByDescent, RequestedInToolResult, TriggeringCommand, TriggeringPrompt, ParentChain, ExecArgs, RawJson) \
        _mcgen_TEMPLATE_FOR_EVT_PROCESS_EXEC(&FISHBOWL_PROVIDER_Context, &EVT_PROCESS_EXEC, Timestamp, HostId, AgentId, UserId, Pid, Ppid, ProcessName, ProcessPath, CommandLine, User, AgentRootPid, AttributedByDescent, RequestedInToolResult, TriggeringCommand, TriggeringPrompt, ParentChain, ExecArgs, RawJson)
#define EventWriteEVT_PROCESS_EXEC_ForContext(pContext, Timestamp, HostId, AgentId, UserId, Pid, Ppid, ProcessName, ProcessPath, CommandLine, User, AgentRootPid, AttributedByDescent, RequestedInToolResult, TriggeringCommand, TriggeringPrompt, ParentChain, ExecArgs, RawJson) \
        MCGEN_EVENT_ENABLED_FORCONTEXT(pContext, EVT_PROCESS_EXEC) \
        ? _mcgen_TEMPLATE_FOR_EVT_PROCESS_EXEC(&(pContext)->Context, &EVT_PROCESS_EXEC, Timestamp, HostId, AgentId, UserId, Pid, Ppid, ProcessName, ProcessPath, CommandLine, User, AgentRootPid, AttributedByDescent, RequestedInToolResult, TriggeringCommand, TriggeringPrompt, ParentChain, ExecArgs, RawJson) : 0
#define EventWriteEVT_PROCESS_EXEC_ForContextAssumeEnabled(pContext, Timestamp, HostId, AgentId, UserId, Pid, Ppid, ProcessName, ProcessPath, CommandLine, User, AgentRootPid, AttributedByDescent, RequestedInToolResult, TriggeringCommand, TriggeringPrompt, ParentChain, ExecArgs, RawJson) \
        _mcgen_TEMPLATE_FOR_EVT_PROCESS_EXEC(&_mcgen_CheckContextType_Fishbowl(pContext)->Context, &EVT_PROCESS_EXEC, Timestamp, HostId, AgentId, UserId, Pid, Ppid, ProcessName, ProcessPath, CommandLine, User, AgentRootPid, AttributedByDescent, RequestedInToolResult, TriggeringCommand, TriggeringPrompt, ParentChain, ExecArgs, RawJson)

// This macro is for use by MC-generated code and should not be used directly.
#define _mcgen_TEMPLATE_FOR_EVT_PROCESS_EXEC _mcgen_PASTE2(McTemplateU0zzzzddzzzzdzzzzzzz_, MCGEN_EVENTWRITETRANSFER)

//
// Enablement check macro for event "EVT_PROCESS_EXIT"
//
#define EventEnabledEVT_PROCESS_EXIT() _mcgen_EVENT_BIT_SET(FishbowlEnableBits, 0)
#define EventEnabledEVT_PROCESS_EXIT_ForContext(pContext) _mcgen_EVENT_BIT_SET(_mcgen_CheckContextType_Fishbowl(pContext)->EnableBits, 0)

//
// Event write macros for event "EVT_PROCESS_EXIT"
//
#define EventWriteEVT_PROCESS_EXIT(Timestamp, HostId, AgentId, Pid, RawJson) \
        MCGEN_EVENT_ENABLED(EVT_PROCESS_EXIT) \
        ? _mcgen_TEMPLATE_FOR_EVT_PROCESS_EXIT(&FISHBOWL_PROVIDER_Context, &EVT_PROCESS_EXIT, Timestamp, HostId, AgentId, Pid, RawJson) : 0
#define EventWriteEVT_PROCESS_EXIT_AssumeEnabled(Timestamp, HostId, AgentId, Pid, RawJson) \
        _mcgen_TEMPLATE_FOR_EVT_PROCESS_EXIT(&FISHBOWL_PROVIDER_Context, &EVT_PROCESS_EXIT, Timestamp, HostId, AgentId, Pid, RawJson)
#define EventWriteEVT_PROCESS_EXIT_ForContext(pContext, Timestamp, HostId, AgentId, Pid, RawJson) \
        MCGEN_EVENT_ENABLED_FORCONTEXT(pContext, EVT_PROCESS_EXIT) \
        ? _mcgen_TEMPLATE_FOR_EVT_PROCESS_EXIT(&(pContext)->Context, &EVT_PROCESS_EXIT, Timestamp, HostId, AgentId, Pid, RawJson) : 0
#define EventWriteEVT_PROCESS_EXIT_ForContextAssumeEnabled(pContext, Timestamp, HostId, AgentId, Pid, RawJson) \
        _mcgen_TEMPLATE_FOR_EVT_PROCESS_EXIT(&_mcgen_CheckContextType_Fishbowl(pContext)->Context, &EVT_PROCESS_EXIT, Timestamp, HostId, AgentId, Pid, RawJson)

// This macro is for use by MC-generated code and should not be used directly.
#define _mcgen_TEMPLATE_FOR_EVT_PROCESS_EXIT _mcgen_PASTE2(McTemplateU0zzzdz_, MCGEN_EVENTWRITETRANSFER)

//
// Enablement check macro for event "EVT_CREDENTIAL_ACCESS"
//
#define EventEnabledEVT_CREDENTIAL_ACCESS() _mcgen_EVENT_BIT_SET(FishbowlEnableBits, 1)
#define EventEnabledEVT_CREDENTIAL_ACCESS_ForContext(pContext) _mcgen_EVENT_BIT_SET(_mcgen_CheckContextType_Fishbowl(pContext)->EnableBits, 1)

//
// Event write macros for event "EVT_CREDENTIAL_ACCESS"
//
#define EventWriteEVT_CREDENTIAL_ACCESS(Timestamp, HostId, AgentId, UserId, Pid, Ppid, ProcessName, ProcessPath, CommandLine, User, AgentRootPid, AttributedByDescent, RequestedInToolResult, TriggeringCommand, TriggeringPrompt, ParentChain, FilePath, CredentialClass, AccessType, RawJson) \
        MCGEN_EVENT_ENABLED(EVT_CREDENTIAL_ACCESS) \
        ? _mcgen_TEMPLATE_FOR_EVT_CREDENTIAL_ACCESS(&FISHBOWL_PROVIDER_Context, &EVT_CREDENTIAL_ACCESS, Timestamp, HostId, AgentId, UserId, Pid, Ppid, ProcessName, ProcessPath, CommandLine, User, AgentRootPid, AttributedByDescent, RequestedInToolResult, TriggeringCommand, TriggeringPrompt, ParentChain, FilePath, CredentialClass, AccessType, RawJson) : 0
#define EventWriteEVT_CREDENTIAL_ACCESS_AssumeEnabled(Timestamp, HostId, AgentId, UserId, Pid, Ppid, ProcessName, ProcessPath, CommandLine, User, AgentRootPid, AttributedByDescent, RequestedInToolResult, TriggeringCommand, TriggeringPrompt, ParentChain, FilePath, CredentialClass, AccessType, RawJson) \
        _mcgen_TEMPLATE_FOR_EVT_CREDENTIAL_ACCESS(&FISHBOWL_PROVIDER_Context, &EVT_CREDENTIAL_ACCESS, Timestamp, HostId, AgentId, UserId, Pid, Ppid, ProcessName, ProcessPath, CommandLine, User, AgentRootPid, AttributedByDescent, RequestedInToolResult, TriggeringCommand, TriggeringPrompt, ParentChain, FilePath, CredentialClass, AccessType, RawJson)
#define EventWriteEVT_CREDENTIAL_ACCESS_ForContext(pContext, Timestamp, HostId, AgentId, UserId, Pid, Ppid, ProcessName, ProcessPath, CommandLine, User, AgentRootPid, AttributedByDescent, RequestedInToolResult, TriggeringCommand, TriggeringPrompt, ParentChain, FilePath, CredentialClass, AccessType, RawJson) \
        MCGEN_EVENT_ENABLED_FORCONTEXT(pContext, EVT_CREDENTIAL_ACCESS) \
        ? _mcgen_TEMPLATE_FOR_EVT_CREDENTIAL_ACCESS(&(pContext)->Context, &EVT_CREDENTIAL_ACCESS, Timestamp, HostId, AgentId, UserId, Pid, Ppid, ProcessName, ProcessPath, CommandLine, User, AgentRootPid, AttributedByDescent, RequestedInToolResult, TriggeringCommand, TriggeringPrompt, ParentChain, FilePath, CredentialClass, AccessType, RawJson) : 0
#define EventWriteEVT_CREDENTIAL_ACCESS_ForContextAssumeEnabled(pContext, Timestamp, HostId, AgentId, UserId, Pid, Ppid, ProcessName, ProcessPath, CommandLine, User, AgentRootPid, AttributedByDescent, RequestedInToolResult, TriggeringCommand, TriggeringPrompt, ParentChain, FilePath, CredentialClass, AccessType, RawJson) \
        _mcgen_TEMPLATE_FOR_EVT_CREDENTIAL_ACCESS(&_mcgen_CheckContextType_Fishbowl(pContext)->Context, &EVT_CREDENTIAL_ACCESS, Timestamp, HostId, AgentId, UserId, Pid, Ppid, ProcessName, ProcessPath, CommandLine, User, AgentRootPid, AttributedByDescent, RequestedInToolResult, TriggeringCommand, TriggeringPrompt, ParentChain, FilePath, CredentialClass, AccessType, RawJson)

// This macro is for use by MC-generated code and should not be used directly.
#define _mcgen_TEMPLATE_FOR_EVT_CREDENTIAL_ACCESS _mcgen_PASTE2(McTemplateU0zzzzddzzzzdzzzzzzzzz_, MCGEN_EVENTWRITETRANSFER)

//
// Enablement check macro for event "EVT_NETWORK_EGRESS"
//
#define EventEnabledEVT_NETWORK_EGRESS() _mcgen_EVENT_BIT_SET(FishbowlEnableBits, 1)
#define EventEnabledEVT_NETWORK_EGRESS_ForContext(pContext) _mcgen_EVENT_BIT_SET(_mcgen_CheckContextType_Fishbowl(pContext)->EnableBits, 1)

//
// Event write macros for event "EVT_NETWORK_EGRESS"
//
#define EventWriteEVT_NETWORK_EGRESS(Timestamp, HostId, AgentId, UserId, Pid, Ppid, ProcessName, ProcessPath, CommandLine, User, AgentRootPid, AttributedByDescent, RequestedInToolResult, TriggeringCommand, TriggeringPrompt, ParentChain, DestIp, DestPort, Protocol, DestHost, RawJson) \
        MCGEN_EVENT_ENABLED(EVT_NETWORK_EGRESS) \
        ? _mcgen_TEMPLATE_FOR_EVT_NETWORK_EGRESS(&FISHBOWL_PROVIDER_Context, &EVT_NETWORK_EGRESS, Timestamp, HostId, AgentId, UserId, Pid, Ppid, ProcessName, ProcessPath, CommandLine, User, AgentRootPid, AttributedByDescent, RequestedInToolResult, TriggeringCommand, TriggeringPrompt, ParentChain, DestIp, DestPort, Protocol, DestHost, RawJson) : 0
#define EventWriteEVT_NETWORK_EGRESS_AssumeEnabled(Timestamp, HostId, AgentId, UserId, Pid, Ppid, ProcessName, ProcessPath, CommandLine, User, AgentRootPid, AttributedByDescent, RequestedInToolResult, TriggeringCommand, TriggeringPrompt, ParentChain, DestIp, DestPort, Protocol, DestHost, RawJson) \
        _mcgen_TEMPLATE_FOR_EVT_NETWORK_EGRESS(&FISHBOWL_PROVIDER_Context, &EVT_NETWORK_EGRESS, Timestamp, HostId, AgentId, UserId, Pid, Ppid, ProcessName, ProcessPath, CommandLine, User, AgentRootPid, AttributedByDescent, RequestedInToolResult, TriggeringCommand, TriggeringPrompt, ParentChain, DestIp, DestPort, Protocol, DestHost, RawJson)
#define EventWriteEVT_NETWORK_EGRESS_ForContext(pContext, Timestamp, HostId, AgentId, UserId, Pid, Ppid, ProcessName, ProcessPath, CommandLine, User, AgentRootPid, AttributedByDescent, RequestedInToolResult, TriggeringCommand, TriggeringPrompt, ParentChain, DestIp, DestPort, Protocol, DestHost, RawJson) \
        MCGEN_EVENT_ENABLED_FORCONTEXT(pContext, EVT_NETWORK_EGRESS) \
        ? _mcgen_TEMPLATE_FOR_EVT_NETWORK_EGRESS(&(pContext)->Context, &EVT_NETWORK_EGRESS, Timestamp, HostId, AgentId, UserId, Pid, Ppid, ProcessName, ProcessPath, CommandLine, User, AgentRootPid, AttributedByDescent, RequestedInToolResult, TriggeringCommand, TriggeringPrompt, ParentChain, DestIp, DestPort, Protocol, DestHost, RawJson) : 0
#define EventWriteEVT_NETWORK_EGRESS_ForContextAssumeEnabled(pContext, Timestamp, HostId, AgentId, UserId, Pid, Ppid, ProcessName, ProcessPath, CommandLine, User, AgentRootPid, AttributedByDescent, RequestedInToolResult, TriggeringCommand, TriggeringPrompt, ParentChain, DestIp, DestPort, Protocol, DestHost, RawJson) \
        _mcgen_TEMPLATE_FOR_EVT_NETWORK_EGRESS(&_mcgen_CheckContextType_Fishbowl(pContext)->Context, &EVT_NETWORK_EGRESS, Timestamp, HostId, AgentId, UserId, Pid, Ppid, ProcessName, ProcessPath, CommandLine, User, AgentRootPid, AttributedByDescent, RequestedInToolResult, TriggeringCommand, TriggeringPrompt, ParentChain, DestIp, DestPort, Protocol, DestHost, RawJson)

// This macro is for use by MC-generated code and should not be used directly.
#define _mcgen_TEMPLATE_FOR_EVT_NETWORK_EGRESS _mcgen_PASTE2(McTemplateU0zzzzddzzzzdzzzzzzdzzz_, MCGEN_EVENTWRITETRANSFER)

//
// Enablement check macro for event "EVT_FILE_WRITE"
//
#define EventEnabledEVT_FILE_WRITE() _mcgen_EVENT_BIT_SET(FishbowlEnableBits, 0)
#define EventEnabledEVT_FILE_WRITE_ForContext(pContext) _mcgen_EVENT_BIT_SET(_mcgen_CheckContextType_Fishbowl(pContext)->EnableBits, 0)

//
// Event write macros for event "EVT_FILE_WRITE"
//
#define EventWriteEVT_FILE_WRITE(Timestamp, HostId, AgentId, Pid, RawJson) \
        MCGEN_EVENT_ENABLED(EVT_FILE_WRITE) \
        ? _mcgen_TEMPLATE_FOR_EVT_FILE_WRITE(&FISHBOWL_PROVIDER_Context, &EVT_FILE_WRITE, Timestamp, HostId, AgentId, Pid, RawJson) : 0
#define EventWriteEVT_FILE_WRITE_AssumeEnabled(Timestamp, HostId, AgentId, Pid, RawJson) \
        _mcgen_TEMPLATE_FOR_EVT_FILE_WRITE(&FISHBOWL_PROVIDER_Context, &EVT_FILE_WRITE, Timestamp, HostId, AgentId, Pid, RawJson)
#define EventWriteEVT_FILE_WRITE_ForContext(pContext, Timestamp, HostId, AgentId, Pid, RawJson) \
        MCGEN_EVENT_ENABLED_FORCONTEXT(pContext, EVT_FILE_WRITE) \
        ? _mcgen_TEMPLATE_FOR_EVT_FILE_WRITE(&(pContext)->Context, &EVT_FILE_WRITE, Timestamp, HostId, AgentId, Pid, RawJson) : 0
#define EventWriteEVT_FILE_WRITE_ForContextAssumeEnabled(pContext, Timestamp, HostId, AgentId, Pid, RawJson) \
        _mcgen_TEMPLATE_FOR_EVT_FILE_WRITE(&_mcgen_CheckContextType_Fishbowl(pContext)->Context, &EVT_FILE_WRITE, Timestamp, HostId, AgentId, Pid, RawJson)

// This macro is for use by MC-generated code and should not be used directly.
#define _mcgen_TEMPLATE_FOR_EVT_FILE_WRITE _mcgen_PASTE2(McTemplateU0zzzdz_, MCGEN_EVENTWRITETRANSFER)

//
// Enablement check macro for event "EVT_PROMPT"
//
#define EventEnabledEVT_PROMPT() _mcgen_EVENT_BIT_SET(FishbowlEnableBits, 0)
#define EventEnabledEVT_PROMPT_ForContext(pContext) _mcgen_EVENT_BIT_SET(_mcgen_CheckContextType_Fishbowl(pContext)->EnableBits, 0)

//
// Event write macros for event "EVT_PROMPT"
//
#define EventWriteEVT_PROMPT(Timestamp, HostId, AgentId, UserId, SessionId, Role, PromptSummary, RawJson) \
        MCGEN_EVENT_ENABLED(EVT_PROMPT) \
        ? _mcgen_TEMPLATE_FOR_EVT_PROMPT(&FISHBOWL_PROVIDER_Context, &EVT_PROMPT, Timestamp, HostId, AgentId, UserId, SessionId, Role, PromptSummary, RawJson) : 0
#define EventWriteEVT_PROMPT_AssumeEnabled(Timestamp, HostId, AgentId, UserId, SessionId, Role, PromptSummary, RawJson) \
        _mcgen_TEMPLATE_FOR_EVT_PROMPT(&FISHBOWL_PROVIDER_Context, &EVT_PROMPT, Timestamp, HostId, AgentId, UserId, SessionId, Role, PromptSummary, RawJson)
#define EventWriteEVT_PROMPT_ForContext(pContext, Timestamp, HostId, AgentId, UserId, SessionId, Role, PromptSummary, RawJson) \
        MCGEN_EVENT_ENABLED_FORCONTEXT(pContext, EVT_PROMPT) \
        ? _mcgen_TEMPLATE_FOR_EVT_PROMPT(&(pContext)->Context, &EVT_PROMPT, Timestamp, HostId, AgentId, UserId, SessionId, Role, PromptSummary, RawJson) : 0
#define EventWriteEVT_PROMPT_ForContextAssumeEnabled(pContext, Timestamp, HostId, AgentId, UserId, SessionId, Role, PromptSummary, RawJson) \
        _mcgen_TEMPLATE_FOR_EVT_PROMPT(&_mcgen_CheckContextType_Fishbowl(pContext)->Context, &EVT_PROMPT, Timestamp, HostId, AgentId, UserId, SessionId, Role, PromptSummary, RawJson)

// This macro is for use by MC-generated code and should not be used directly.
#define _mcgen_TEMPLATE_FOR_EVT_PROMPT _mcgen_PASTE2(McTemplateU0zzzzzzzz_, MCGEN_EVENTWRITETRANSFER)

//
// Enablement check macro for event "EVT_TOOL_CALL"
//
#define EventEnabledEVT_TOOL_CALL() _mcgen_EVENT_BIT_SET(FishbowlEnableBits, 0)
#define EventEnabledEVT_TOOL_CALL_ForContext(pContext) _mcgen_EVENT_BIT_SET(_mcgen_CheckContextType_Fishbowl(pContext)->EnableBits, 0)

//
// Event write macros for event "EVT_TOOL_CALL"
//
#define EventWriteEVT_TOOL_CALL(Timestamp, HostId, AgentId, UserId, SessionId, ToolName, ToolCallId, ToolInputSummary, RawJson) \
        MCGEN_EVENT_ENABLED(EVT_TOOL_CALL) \
        ? _mcgen_TEMPLATE_FOR_EVT_TOOL_CALL(&FISHBOWL_PROVIDER_Context, &EVT_TOOL_CALL, Timestamp, HostId, AgentId, UserId, SessionId, ToolName, ToolCallId, ToolInputSummary, RawJson) : 0
#define EventWriteEVT_TOOL_CALL_AssumeEnabled(Timestamp, HostId, AgentId, UserId, SessionId, ToolName, ToolCallId, ToolInputSummary, RawJson) \
        _mcgen_TEMPLATE_FOR_EVT_TOOL_CALL(&FISHBOWL_PROVIDER_Context, &EVT_TOOL_CALL, Timestamp, HostId, AgentId, UserId, SessionId, ToolName, ToolCallId, ToolInputSummary, RawJson)
#define EventWriteEVT_TOOL_CALL_ForContext(pContext, Timestamp, HostId, AgentId, UserId, SessionId, ToolName, ToolCallId, ToolInputSummary, RawJson) \
        MCGEN_EVENT_ENABLED_FORCONTEXT(pContext, EVT_TOOL_CALL) \
        ? _mcgen_TEMPLATE_FOR_EVT_TOOL_CALL(&(pContext)->Context, &EVT_TOOL_CALL, Timestamp, HostId, AgentId, UserId, SessionId, ToolName, ToolCallId, ToolInputSummary, RawJson) : 0
#define EventWriteEVT_TOOL_CALL_ForContextAssumeEnabled(pContext, Timestamp, HostId, AgentId, UserId, SessionId, ToolName, ToolCallId, ToolInputSummary, RawJson) \
        _mcgen_TEMPLATE_FOR_EVT_TOOL_CALL(&_mcgen_CheckContextType_Fishbowl(pContext)->Context, &EVT_TOOL_CALL, Timestamp, HostId, AgentId, UserId, SessionId, ToolName, ToolCallId, ToolInputSummary, RawJson)

// This macro is for use by MC-generated code and should not be used directly.
#define _mcgen_TEMPLATE_FOR_EVT_TOOL_CALL _mcgen_PASTE2(McTemplateU0zzzzzzzzz_, MCGEN_EVENTWRITETRANSFER)

//
// Enablement check macro for event "EVT_TOOL_RESULT"
//
#define EventEnabledEVT_TOOL_RESULT() _mcgen_EVENT_BIT_SET(FishbowlEnableBits, 0)
#define EventEnabledEVT_TOOL_RESULT_ForContext(pContext) _mcgen_EVENT_BIT_SET(_mcgen_CheckContextType_Fishbowl(pContext)->EnableBits, 0)

//
// Event write macros for event "EVT_TOOL_RESULT"
//
#define EventWriteEVT_TOOL_RESULT(Timestamp, HostId, AgentId, UserId, SessionId, ToolCallId, ResultStatus, ResultSummary, RawJson) \
        MCGEN_EVENT_ENABLED(EVT_TOOL_RESULT) \
        ? _mcgen_TEMPLATE_FOR_EVT_TOOL_RESULT(&FISHBOWL_PROVIDER_Context, &EVT_TOOL_RESULT, Timestamp, HostId, AgentId, UserId, SessionId, ToolCallId, ResultStatus, ResultSummary, RawJson) : 0
#define EventWriteEVT_TOOL_RESULT_AssumeEnabled(Timestamp, HostId, AgentId, UserId, SessionId, ToolCallId, ResultStatus, ResultSummary, RawJson) \
        _mcgen_TEMPLATE_FOR_EVT_TOOL_RESULT(&FISHBOWL_PROVIDER_Context, &EVT_TOOL_RESULT, Timestamp, HostId, AgentId, UserId, SessionId, ToolCallId, ResultStatus, ResultSummary, RawJson)
#define EventWriteEVT_TOOL_RESULT_ForContext(pContext, Timestamp, HostId, AgentId, UserId, SessionId, ToolCallId, ResultStatus, ResultSummary, RawJson) \
        MCGEN_EVENT_ENABLED_FORCONTEXT(pContext, EVT_TOOL_RESULT) \
        ? _mcgen_TEMPLATE_FOR_EVT_TOOL_RESULT(&(pContext)->Context, &EVT_TOOL_RESULT, Timestamp, HostId, AgentId, UserId, SessionId, ToolCallId, ResultStatus, ResultSummary, RawJson) : 0
#define EventWriteEVT_TOOL_RESULT_ForContextAssumeEnabled(pContext, Timestamp, HostId, AgentId, UserId, SessionId, ToolCallId, ResultStatus, ResultSummary, RawJson) \
        _mcgen_TEMPLATE_FOR_EVT_TOOL_RESULT(&_mcgen_CheckContextType_Fishbowl(pContext)->Context, &EVT_TOOL_RESULT, Timestamp, HostId, AgentId, UserId, SessionId, ToolCallId, ResultStatus, ResultSummary, RawJson)

// This macro is for use by MC-generated code and should not be used directly.
#define _mcgen_TEMPLATE_FOR_EVT_TOOL_RESULT _mcgen_PASTE2(McTemplateU0zzzzzzzzz_, MCGEN_EVENTWRITETRANSFER)

#endif // MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//
// MCGEN_DISABLE_PROVIDER_CODE_GENERATION macro:
// Define this macro to have the compiler skip the generated functions in this
// header.
//
#ifndef MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//
// Template Functions
//

//
// Function for template "t_generic" (and possibly others).
// This function is for use by MC-generated code and should not be used directly.
//
#ifndef McTemplateU0zzzdz_def
#define McTemplateU0zzzdz_def
ETW_INLINE
ULONG
_mcgen_PASTE2(McTemplateU0zzzdz_, MCGEN_EVENTWRITETRANSFER)(
    _In_ PMCGEN_TRACE_CONTEXT Context,
    _In_ PCEVENT_DESCRIPTOR Descriptor,
    _In_opt_ PCWSTR  _Arg0,
    _In_opt_ PCWSTR  _Arg1,
    _In_opt_ PCWSTR  _Arg2,
    _In_ const signed int  _Arg3,
    _In_opt_ PCWSTR  _Arg4
    )
{
#define McTemplateU0zzzdz_ARGCOUNT 5

    EVENT_DATA_DESCRIPTOR EventData[McTemplateU0zzzdz_ARGCOUNT + 1];

    EventDataDescCreate(&EventData[1],
                        (_Arg0 != NULL) ? _Arg0 : L"NULL",
                        (_Arg0 != NULL) ? (ULONG)((wcslen(_Arg0) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[2],
                        (_Arg1 != NULL) ? _Arg1 : L"NULL",
                        (_Arg1 != NULL) ? (ULONG)((wcslen(_Arg1) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[3],
                        (_Arg2 != NULL) ? _Arg2 : L"NULL",
                        (_Arg2 != NULL) ? (ULONG)((wcslen(_Arg2) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[4],&_Arg3, sizeof(const signed int)  );

    EventDataDescCreate(&EventData[5],
                        (_Arg4 != NULL) ? _Arg4 : L"NULL",
                        (_Arg4 != NULL) ? (ULONG)((wcslen(_Arg4) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    return McGenEventWrite(Context, Descriptor, NULL, McTemplateU0zzzdz_ARGCOUNT + 1, EventData);
}
#endif // McTemplateU0zzzdz_def

//
// Function for template "t_net" (and possibly others).
// This function is for use by MC-generated code and should not be used directly.
//
#ifndef McTemplateU0zzzzddzzzzdzzzzzzdzzz_def
#define McTemplateU0zzzzddzzzzdzzzzzzdzzz_def
ETW_INLINE
ULONG
_mcgen_PASTE2(McTemplateU0zzzzddzzzzdzzzzzzdzzz_, MCGEN_EVENTWRITETRANSFER)(
    _In_ PMCGEN_TRACE_CONTEXT Context,
    _In_ PCEVENT_DESCRIPTOR Descriptor,
    _In_opt_ PCWSTR  _Arg0,
    _In_opt_ PCWSTR  _Arg1,
    _In_opt_ PCWSTR  _Arg2,
    _In_opt_ PCWSTR  _Arg3,
    _In_ const signed int  _Arg4,
    _In_ const signed int  _Arg5,
    _In_opt_ PCWSTR  _Arg6,
    _In_opt_ PCWSTR  _Arg7,
    _In_opt_ PCWSTR  _Arg8,
    _In_opt_ PCWSTR  _Arg9,
    _In_ const signed int  _Arg10,
    _In_opt_ PCWSTR  _Arg11,
    _In_opt_ PCWSTR  _Arg12,
    _In_opt_ PCWSTR  _Arg13,
    _In_opt_ PCWSTR  _Arg14,
    _In_opt_ PCWSTR  _Arg15,
    _In_opt_ PCWSTR  _Arg16,
    _In_ const signed int  _Arg17,
    _In_opt_ PCWSTR  _Arg18,
    _In_opt_ PCWSTR  _Arg19,
    _In_opt_ PCWSTR  _Arg20
    )
{
#define McTemplateU0zzzzddzzzzdzzzzzzdzzz_ARGCOUNT 21

    EVENT_DATA_DESCRIPTOR EventData[McTemplateU0zzzzddzzzzdzzzzzzdzzz_ARGCOUNT + 1];

    EventDataDescCreate(&EventData[1],
                        (_Arg0 != NULL) ? _Arg0 : L"NULL",
                        (_Arg0 != NULL) ? (ULONG)((wcslen(_Arg0) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[2],
                        (_Arg1 != NULL) ? _Arg1 : L"NULL",
                        (_Arg1 != NULL) ? (ULONG)((wcslen(_Arg1) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[3],
                        (_Arg2 != NULL) ? _Arg2 : L"NULL",
                        (_Arg2 != NULL) ? (ULONG)((wcslen(_Arg2) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[4],
                        (_Arg3 != NULL) ? _Arg3 : L"NULL",
                        (_Arg3 != NULL) ? (ULONG)((wcslen(_Arg3) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[5],&_Arg4, sizeof(const signed int)  );

    EventDataDescCreate(&EventData[6],&_Arg5, sizeof(const signed int)  );

    EventDataDescCreate(&EventData[7],
                        (_Arg6 != NULL) ? _Arg6 : L"NULL",
                        (_Arg6 != NULL) ? (ULONG)((wcslen(_Arg6) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[8],
                        (_Arg7 != NULL) ? _Arg7 : L"NULL",
                        (_Arg7 != NULL) ? (ULONG)((wcslen(_Arg7) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[9],
                        (_Arg8 != NULL) ? _Arg8 : L"NULL",
                        (_Arg8 != NULL) ? (ULONG)((wcslen(_Arg8) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[10],
                        (_Arg9 != NULL) ? _Arg9 : L"NULL",
                        (_Arg9 != NULL) ? (ULONG)((wcslen(_Arg9) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[11],&_Arg10, sizeof(const signed int)  );

    EventDataDescCreate(&EventData[12],
                        (_Arg11 != NULL) ? _Arg11 : L"NULL",
                        (_Arg11 != NULL) ? (ULONG)((wcslen(_Arg11) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[13],
                        (_Arg12 != NULL) ? _Arg12 : L"NULL",
                        (_Arg12 != NULL) ? (ULONG)((wcslen(_Arg12) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[14],
                        (_Arg13 != NULL) ? _Arg13 : L"NULL",
                        (_Arg13 != NULL) ? (ULONG)((wcslen(_Arg13) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[15],
                        (_Arg14 != NULL) ? _Arg14 : L"NULL",
                        (_Arg14 != NULL) ? (ULONG)((wcslen(_Arg14) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[16],
                        (_Arg15 != NULL) ? _Arg15 : L"NULL",
                        (_Arg15 != NULL) ? (ULONG)((wcslen(_Arg15) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[17],
                        (_Arg16 != NULL) ? _Arg16 : L"NULL",
                        (_Arg16 != NULL) ? (ULONG)((wcslen(_Arg16) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[18],&_Arg17, sizeof(const signed int)  );

    EventDataDescCreate(&EventData[19],
                        (_Arg18 != NULL) ? _Arg18 : L"NULL",
                        (_Arg18 != NULL) ? (ULONG)((wcslen(_Arg18) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[20],
                        (_Arg19 != NULL) ? _Arg19 : L"NULL",
                        (_Arg19 != NULL) ? (ULONG)((wcslen(_Arg19) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[21],
                        (_Arg20 != NULL) ? _Arg20 : L"NULL",
                        (_Arg20 != NULL) ? (ULONG)((wcslen(_Arg20) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    return McGenEventWrite(Context, Descriptor, NULL, McTemplateU0zzzzddzzzzdzzzzzzdzzz_ARGCOUNT + 1, EventData);
}
#endif // McTemplateU0zzzzddzzzzdzzzzzzdzzz_def

//
// Function for template "t_proc_exec" (and possibly others).
// This function is for use by MC-generated code and should not be used directly.
//
#ifndef McTemplateU0zzzzddzzzzdzzzzzzz_def
#define McTemplateU0zzzzddzzzzdzzzzzzz_def
ETW_INLINE
ULONG
_mcgen_PASTE2(McTemplateU0zzzzddzzzzdzzzzzzz_, MCGEN_EVENTWRITETRANSFER)(
    _In_ PMCGEN_TRACE_CONTEXT Context,
    _In_ PCEVENT_DESCRIPTOR Descriptor,
    _In_opt_ PCWSTR  _Arg0,
    _In_opt_ PCWSTR  _Arg1,
    _In_opt_ PCWSTR  _Arg2,
    _In_opt_ PCWSTR  _Arg3,
    _In_ const signed int  _Arg4,
    _In_ const signed int  _Arg5,
    _In_opt_ PCWSTR  _Arg6,
    _In_opt_ PCWSTR  _Arg7,
    _In_opt_ PCWSTR  _Arg8,
    _In_opt_ PCWSTR  _Arg9,
    _In_ const signed int  _Arg10,
    _In_opt_ PCWSTR  _Arg11,
    _In_opt_ PCWSTR  _Arg12,
    _In_opt_ PCWSTR  _Arg13,
    _In_opt_ PCWSTR  _Arg14,
    _In_opt_ PCWSTR  _Arg15,
    _In_opt_ PCWSTR  _Arg16,
    _In_opt_ PCWSTR  _Arg17
    )
{
#define McTemplateU0zzzzddzzzzdzzzzzzz_ARGCOUNT 18

    EVENT_DATA_DESCRIPTOR EventData[McTemplateU0zzzzddzzzzdzzzzzzz_ARGCOUNT + 1];

    EventDataDescCreate(&EventData[1],
                        (_Arg0 != NULL) ? _Arg0 : L"NULL",
                        (_Arg0 != NULL) ? (ULONG)((wcslen(_Arg0) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[2],
                        (_Arg1 != NULL) ? _Arg1 : L"NULL",
                        (_Arg1 != NULL) ? (ULONG)((wcslen(_Arg1) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[3],
                        (_Arg2 != NULL) ? _Arg2 : L"NULL",
                        (_Arg2 != NULL) ? (ULONG)((wcslen(_Arg2) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[4],
                        (_Arg3 != NULL) ? _Arg3 : L"NULL",
                        (_Arg3 != NULL) ? (ULONG)((wcslen(_Arg3) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[5],&_Arg4, sizeof(const signed int)  );

    EventDataDescCreate(&EventData[6],&_Arg5, sizeof(const signed int)  );

    EventDataDescCreate(&EventData[7],
                        (_Arg6 != NULL) ? _Arg6 : L"NULL",
                        (_Arg6 != NULL) ? (ULONG)((wcslen(_Arg6) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[8],
                        (_Arg7 != NULL) ? _Arg7 : L"NULL",
                        (_Arg7 != NULL) ? (ULONG)((wcslen(_Arg7) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[9],
                        (_Arg8 != NULL) ? _Arg8 : L"NULL",
                        (_Arg8 != NULL) ? (ULONG)((wcslen(_Arg8) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[10],
                        (_Arg9 != NULL) ? _Arg9 : L"NULL",
                        (_Arg9 != NULL) ? (ULONG)((wcslen(_Arg9) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[11],&_Arg10, sizeof(const signed int)  );

    EventDataDescCreate(&EventData[12],
                        (_Arg11 != NULL) ? _Arg11 : L"NULL",
                        (_Arg11 != NULL) ? (ULONG)((wcslen(_Arg11) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[13],
                        (_Arg12 != NULL) ? _Arg12 : L"NULL",
                        (_Arg12 != NULL) ? (ULONG)((wcslen(_Arg12) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[14],
                        (_Arg13 != NULL) ? _Arg13 : L"NULL",
                        (_Arg13 != NULL) ? (ULONG)((wcslen(_Arg13) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[15],
                        (_Arg14 != NULL) ? _Arg14 : L"NULL",
                        (_Arg14 != NULL) ? (ULONG)((wcslen(_Arg14) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[16],
                        (_Arg15 != NULL) ? _Arg15 : L"NULL",
                        (_Arg15 != NULL) ? (ULONG)((wcslen(_Arg15) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[17],
                        (_Arg16 != NULL) ? _Arg16 : L"NULL",
                        (_Arg16 != NULL) ? (ULONG)((wcslen(_Arg16) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[18],
                        (_Arg17 != NULL) ? _Arg17 : L"NULL",
                        (_Arg17 != NULL) ? (ULONG)((wcslen(_Arg17) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    return McGenEventWrite(Context, Descriptor, NULL, McTemplateU0zzzzddzzzzdzzzzzzz_ARGCOUNT + 1, EventData);
}
#endif // McTemplateU0zzzzddzzzzdzzzzzzz_def

//
// Function for template "t_cred" (and possibly others).
// This function is for use by MC-generated code and should not be used directly.
//
#ifndef McTemplateU0zzzzddzzzzdzzzzzzzzz_def
#define McTemplateU0zzzzddzzzzdzzzzzzzzz_def
ETW_INLINE
ULONG
_mcgen_PASTE2(McTemplateU0zzzzddzzzzdzzzzzzzzz_, MCGEN_EVENTWRITETRANSFER)(
    _In_ PMCGEN_TRACE_CONTEXT Context,
    _In_ PCEVENT_DESCRIPTOR Descriptor,
    _In_opt_ PCWSTR  _Arg0,
    _In_opt_ PCWSTR  _Arg1,
    _In_opt_ PCWSTR  _Arg2,
    _In_opt_ PCWSTR  _Arg3,
    _In_ const signed int  _Arg4,
    _In_ const signed int  _Arg5,
    _In_opt_ PCWSTR  _Arg6,
    _In_opt_ PCWSTR  _Arg7,
    _In_opt_ PCWSTR  _Arg8,
    _In_opt_ PCWSTR  _Arg9,
    _In_ const signed int  _Arg10,
    _In_opt_ PCWSTR  _Arg11,
    _In_opt_ PCWSTR  _Arg12,
    _In_opt_ PCWSTR  _Arg13,
    _In_opt_ PCWSTR  _Arg14,
    _In_opt_ PCWSTR  _Arg15,
    _In_opt_ PCWSTR  _Arg16,
    _In_opt_ PCWSTR  _Arg17,
    _In_opt_ PCWSTR  _Arg18,
    _In_opt_ PCWSTR  _Arg19
    )
{
#define McTemplateU0zzzzddzzzzdzzzzzzzzz_ARGCOUNT 20

    EVENT_DATA_DESCRIPTOR EventData[McTemplateU0zzzzddzzzzdzzzzzzzzz_ARGCOUNT + 1];

    EventDataDescCreate(&EventData[1],
                        (_Arg0 != NULL) ? _Arg0 : L"NULL",
                        (_Arg0 != NULL) ? (ULONG)((wcslen(_Arg0) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[2],
                        (_Arg1 != NULL) ? _Arg1 : L"NULL",
                        (_Arg1 != NULL) ? (ULONG)((wcslen(_Arg1) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[3],
                        (_Arg2 != NULL) ? _Arg2 : L"NULL",
                        (_Arg2 != NULL) ? (ULONG)((wcslen(_Arg2) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[4],
                        (_Arg3 != NULL) ? _Arg3 : L"NULL",
                        (_Arg3 != NULL) ? (ULONG)((wcslen(_Arg3) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[5],&_Arg4, sizeof(const signed int)  );

    EventDataDescCreate(&EventData[6],&_Arg5, sizeof(const signed int)  );

    EventDataDescCreate(&EventData[7],
                        (_Arg6 != NULL) ? _Arg6 : L"NULL",
                        (_Arg6 != NULL) ? (ULONG)((wcslen(_Arg6) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[8],
                        (_Arg7 != NULL) ? _Arg7 : L"NULL",
                        (_Arg7 != NULL) ? (ULONG)((wcslen(_Arg7) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[9],
                        (_Arg8 != NULL) ? _Arg8 : L"NULL",
                        (_Arg8 != NULL) ? (ULONG)((wcslen(_Arg8) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[10],
                        (_Arg9 != NULL) ? _Arg9 : L"NULL",
                        (_Arg9 != NULL) ? (ULONG)((wcslen(_Arg9) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[11],&_Arg10, sizeof(const signed int)  );

    EventDataDescCreate(&EventData[12],
                        (_Arg11 != NULL) ? _Arg11 : L"NULL",
                        (_Arg11 != NULL) ? (ULONG)((wcslen(_Arg11) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[13],
                        (_Arg12 != NULL) ? _Arg12 : L"NULL",
                        (_Arg12 != NULL) ? (ULONG)((wcslen(_Arg12) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[14],
                        (_Arg13 != NULL) ? _Arg13 : L"NULL",
                        (_Arg13 != NULL) ? (ULONG)((wcslen(_Arg13) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[15],
                        (_Arg14 != NULL) ? _Arg14 : L"NULL",
                        (_Arg14 != NULL) ? (ULONG)((wcslen(_Arg14) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[16],
                        (_Arg15 != NULL) ? _Arg15 : L"NULL",
                        (_Arg15 != NULL) ? (ULONG)((wcslen(_Arg15) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[17],
                        (_Arg16 != NULL) ? _Arg16 : L"NULL",
                        (_Arg16 != NULL) ? (ULONG)((wcslen(_Arg16) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[18],
                        (_Arg17 != NULL) ? _Arg17 : L"NULL",
                        (_Arg17 != NULL) ? (ULONG)((wcslen(_Arg17) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[19],
                        (_Arg18 != NULL) ? _Arg18 : L"NULL",
                        (_Arg18 != NULL) ? (ULONG)((wcslen(_Arg18) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[20],
                        (_Arg19 != NULL) ? _Arg19 : L"NULL",
                        (_Arg19 != NULL) ? (ULONG)((wcslen(_Arg19) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    return McGenEventWrite(Context, Descriptor, NULL, McTemplateU0zzzzddzzzzdzzzzzzzzz_ARGCOUNT + 1, EventData);
}
#endif // McTemplateU0zzzzddzzzzdzzzzzzzzz_def

//
// Function for template "t_prompt" (and possibly others).
// This function is for use by MC-generated code and should not be used directly.
//
#ifndef McTemplateU0zzzzzzzz_def
#define McTemplateU0zzzzzzzz_def
ETW_INLINE
ULONG
_mcgen_PASTE2(McTemplateU0zzzzzzzz_, MCGEN_EVENTWRITETRANSFER)(
    _In_ PMCGEN_TRACE_CONTEXT Context,
    _In_ PCEVENT_DESCRIPTOR Descriptor,
    _In_opt_ PCWSTR  _Arg0,
    _In_opt_ PCWSTR  _Arg1,
    _In_opt_ PCWSTR  _Arg2,
    _In_opt_ PCWSTR  _Arg3,
    _In_opt_ PCWSTR  _Arg4,
    _In_opt_ PCWSTR  _Arg5,
    _In_opt_ PCWSTR  _Arg6,
    _In_opt_ PCWSTR  _Arg7
    )
{
#define McTemplateU0zzzzzzzz_ARGCOUNT 8

    EVENT_DATA_DESCRIPTOR EventData[McTemplateU0zzzzzzzz_ARGCOUNT + 1];

    EventDataDescCreate(&EventData[1],
                        (_Arg0 != NULL) ? _Arg0 : L"NULL",
                        (_Arg0 != NULL) ? (ULONG)((wcslen(_Arg0) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[2],
                        (_Arg1 != NULL) ? _Arg1 : L"NULL",
                        (_Arg1 != NULL) ? (ULONG)((wcslen(_Arg1) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[3],
                        (_Arg2 != NULL) ? _Arg2 : L"NULL",
                        (_Arg2 != NULL) ? (ULONG)((wcslen(_Arg2) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[4],
                        (_Arg3 != NULL) ? _Arg3 : L"NULL",
                        (_Arg3 != NULL) ? (ULONG)((wcslen(_Arg3) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[5],
                        (_Arg4 != NULL) ? _Arg4 : L"NULL",
                        (_Arg4 != NULL) ? (ULONG)((wcslen(_Arg4) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[6],
                        (_Arg5 != NULL) ? _Arg5 : L"NULL",
                        (_Arg5 != NULL) ? (ULONG)((wcslen(_Arg5) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[7],
                        (_Arg6 != NULL) ? _Arg6 : L"NULL",
                        (_Arg6 != NULL) ? (ULONG)((wcslen(_Arg6) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[8],
                        (_Arg7 != NULL) ? _Arg7 : L"NULL",
                        (_Arg7 != NULL) ? (ULONG)((wcslen(_Arg7) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    return McGenEventWrite(Context, Descriptor, NULL, McTemplateU0zzzzzzzz_ARGCOUNT + 1, EventData);
}
#endif // McTemplateU0zzzzzzzz_def

//
// Function for template "t_tool_call" (and possibly others).
// This function is for use by MC-generated code and should not be used directly.
//
#ifndef McTemplateU0zzzzzzzzz_def
#define McTemplateU0zzzzzzzzz_def
ETW_INLINE
ULONG
_mcgen_PASTE2(McTemplateU0zzzzzzzzz_, MCGEN_EVENTWRITETRANSFER)(
    _In_ PMCGEN_TRACE_CONTEXT Context,
    _In_ PCEVENT_DESCRIPTOR Descriptor,
    _In_opt_ PCWSTR  _Arg0,
    _In_opt_ PCWSTR  _Arg1,
    _In_opt_ PCWSTR  _Arg2,
    _In_opt_ PCWSTR  _Arg3,
    _In_opt_ PCWSTR  _Arg4,
    _In_opt_ PCWSTR  _Arg5,
    _In_opt_ PCWSTR  _Arg6,
    _In_opt_ PCWSTR  _Arg7,
    _In_opt_ PCWSTR  _Arg8
    )
{
#define McTemplateU0zzzzzzzzz_ARGCOUNT 9

    EVENT_DATA_DESCRIPTOR EventData[McTemplateU0zzzzzzzzz_ARGCOUNT + 1];

    EventDataDescCreate(&EventData[1],
                        (_Arg0 != NULL) ? _Arg0 : L"NULL",
                        (_Arg0 != NULL) ? (ULONG)((wcslen(_Arg0) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[2],
                        (_Arg1 != NULL) ? _Arg1 : L"NULL",
                        (_Arg1 != NULL) ? (ULONG)((wcslen(_Arg1) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[3],
                        (_Arg2 != NULL) ? _Arg2 : L"NULL",
                        (_Arg2 != NULL) ? (ULONG)((wcslen(_Arg2) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[4],
                        (_Arg3 != NULL) ? _Arg3 : L"NULL",
                        (_Arg3 != NULL) ? (ULONG)((wcslen(_Arg3) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[5],
                        (_Arg4 != NULL) ? _Arg4 : L"NULL",
                        (_Arg4 != NULL) ? (ULONG)((wcslen(_Arg4) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[6],
                        (_Arg5 != NULL) ? _Arg5 : L"NULL",
                        (_Arg5 != NULL) ? (ULONG)((wcslen(_Arg5) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[7],
                        (_Arg6 != NULL) ? _Arg6 : L"NULL",
                        (_Arg6 != NULL) ? (ULONG)((wcslen(_Arg6) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[8],
                        (_Arg7 != NULL) ? _Arg7 : L"NULL",
                        (_Arg7 != NULL) ? (ULONG)((wcslen(_Arg7) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    EventDataDescCreate(&EventData[9],
                        (_Arg8 != NULL) ? _Arg8 : L"NULL",
                        (_Arg8 != NULL) ? (ULONG)((wcslen(_Arg8) + 1) * sizeof(WCHAR)) : (ULONG)sizeof(L"NULL"));

    return McGenEventWrite(Context, Descriptor, NULL, McTemplateU0zzzzzzzzz_ARGCOUNT + 1, EventData);
}
#endif // McTemplateU0zzzzzzzzz_def

#endif // MCGEN_DISABLE_PROVIDER_CODE_GENERATION

#if defined(__cplusplus)
}
#endif

#define MSG_task_process_exec                0x70000001L
#define MSG_task_process_exit                0x70000002L
#define MSG_task_credential_access           0x70000003L
#define MSG_task_network_egress              0x70000004L
#define MSG_task_file_write                  0x70000005L
#define MSG_task_prompt                      0x7000000AL
#define MSG_task_tool_call                   0x7000000BL
#define MSG_task_tool_result                 0x7000000CL
#define MSG_evt_process_exec                 0xB0000001L
#define MSG_evt_process_exit                 0xB0000002L
#define MSG_evt_credential_access            0xB0000003L
#define MSG_evt_network_egress               0xB0000004L
#define MSG_evt_file_write                   0xB0000005L
#define MSG_evt_prompt                       0xB000000AL
#define MSG_evt_tool_call                    0xB000000BL
#define MSG_evt_tool_result                  0xB000000CL
